CREATE DATABASE ApiBD;
GO

USE ApiBD;
GO

CREATE TABLE Usuarios_Sistema (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE
);
GO
ALTER TABLE Usuarios_Sistema
ADD CONSTRAINT CK_Role CHECK (Role IN ('Admin', 'Funcionario', 'Gestor'));

-- ALTER TABLE Usuarios_Sistema
-- ADD Senha NVARCHAR(200) NOT NULL DEFAULT('');
